issuer: https://alphastocks.com/tts
audience: https://alphastocks.com/
token:
  lifeTime: "15s"
keys:
  privateKey: ${PRIVATE_KEY}
  jwks: ${JWKS}
  keyID: ${KEY_ID}
spiffe:
  endpoint_socket: unix:///run/spire/sockets/agent.sock
  serviceID: spiffe://alphastocks.com/tts
  authorizedServiceIDs:
    - spiffe://alphastocks.com/gateway
subjectTokens:
  OIDC:
    clientId: alpha-stocks-client
    providerURL: http://dex.dex-ns.svc.cluster.local:5556/dex
    subjectField: email
enableAccessEvaluation: ${ENABLE_ACCESS_EVALUATION}
accessEvaluationAPI:
  endpoint: https://authzen.sgnlapis.cloud/access/v1/evaluation
  authentication:
    method: Bearer
    token:
      value: ${ACCESS_EVALUATION_API_BEARER_TOKEN}
  requestMapping:
    subject:
      id: "$.subject_token.email"
    action:
      name: "$.scope"
    resource:
      stockID: "$.request_details.stockID"
      transactionID: "$.request_details.transactionID"
    context: "$.request_context"