issuer: "http://dex:5556/dex"
storage:
  type: sqlite3
  config:
    file: /tmp/dex.db
web:
  http: 0.0.0.0:5556
logger:
  level: "debug"

staticClients:
- id: 'alpha-stocks-client'
  redirectURIs:
  - 'http://localhost:4200/callback'
  name: 'Alpha Stocks'
  secret: MV9zf+XnZvs/nJy4Z+ya7A== # Replace this value for your installation

# The default password for all users below is password123
enablePasswordDB: true
staticPasswords:
- email: "sherlock@detect.com"
  hash: "$2a$12$qzD.zI2dNelNr2JmUXwmgee2CaAleLtP5gjt4bXmAPLma4A/ALpza"
  username: "sherlock"
  userID: "0001"
- email: "diana@amazonian.com"
  hash: "$2a$12$qzD.zI2dNelNr2JmUXwmgee2CaAleLtP5gjt4bXmAPLma4A/ALpza"
  username: "diana"
  userID: "0002"
- email: "neo@matrix.com"
  hash: "$2a$12$qzD.zI2dNelNr2JmUXwmgee2CaAleLtP5gjt4bXmAPLma4A/ALpza"
  username: "neo"
  userID: "0003"
- email: "hermione@magic.com"
  hash: "$2a$12$qzD.zI2dNelNr2JmUXwmgee2CaAleLtP5gjt4bXmAPLma4A/ALpza"
  username: "hermione"
  userID: "0004"
- email: "HAL9000@ai.com"
  hash: "$2a$12$qzD.zI2dNelNr2JmUXwmgee2CaAleLtP5gjt4bXmAPLma4A/ALpza"
  username: "HAL9000"
  userID: "0005"
