apiVersion: tokenetes.io/v1alpha1
kind: TraT
metadata:
  name: stock-details-api-trat
  namespace: alpha-stocks-dev
spec:
  path: "/api/stocks/details/{#stockId}"
  method: "GET"
  purp: stock-details
  azdMapping:
    stockId:
      required: true
      value: "${stockId}"
  services:
    - name: stocks
  accessEvaluation:
    subject:
      id: "${subject_token.email}"
    action:
      name: "stock-details"
    resource:
      stockId: "${stockId}"