apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: alpha-stocks
spec:
  type: NodePort
  ports:
    - name: "30000"
      port: 30000
      targetPort: 30000
      nodePort: 30000
  selector:
    app: gateway
