apiVersion: apps/v1
kind: Deployment
metadata:
  name: tratteria
  namespace: alpha-stocks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tratteria
  template:
    metadata:
      labels:
        app: tratteria
    spec:
      serviceAccountName: tratteria-service-account
      containers:
        - image: tratteria
          name: tratteria
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /run/spire/sockets
              name: spire-agent-socket
              readOnly: true
          env:
            - name: TCONFIGD_URL
              value: https://tconfigd.tratteria-system.svc.cluster.local:8443
            - name: TCONFIGD_SPIFFE_ID
              value: spiffe://alphastocks.com/tconfigd
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: MY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: Always
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
