apiVersion: tratteria.io/v1alpha1
kind: TraT
metadata:
  name: stock-search-api-trat
  namespace: alpha-stocks-dev
spec:
  path: "/api/stocks/search"
  method: "GET"
  purp: stock-search
  azdMapping:
    query:
      required: true
      value: "${queryParameters.query}"
  services:
    - name: stocks
  accessEvaluation:
    subject:
      id: "${subject_token.email}"
    action:
      name: "stock-search"
    resource:
      query: "${queryParameters.query}"