apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: alpha-stocks-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: gateway-service-account
      containers:
        - env:
            - name: TOKENETES_URL
              value: https://tokenetes:443
            - name: ORDER_SERVICE_URL
              value: http://order:8090
            - name: STOCKS_SERVICE_URL
              value: http://stocks:8070
            - name: OAUTH2_CLIENT_ID
              value: alpha-stocks-client
            - name: OAUTH2_CLIENT_SECRET
              value: MV9zf+XnZvs/nJy4Z+ya7A== # Replace this value for your installation
            - name: OAUTH2_REDIRECT_URL
              value: http://localhost:4200/callback
            - name: OAUTH2_TOKEN_URL
              value: http://dex:5556/dex/token
            - name: OIDC_ISSUER_URL
              value: http://dex:5556/dex
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: TOKENETES_SPIFFE_ID
              value: spiffe://dev.alphastocks.com/tokenetes
            - name: ORDER_SERVICE_SPIFFE_ID
              value: spiffe://dev.alphastocks.com/order
            - name: STOCKS_SERVICE_SPIFFE_ID
              value: spiffe://dev.alphastocks.com/stocks
            - name: ENABLE_TRATS
              value: "${ENABLE_TRATS}"
          image: ghcr.io/tokenetes/example-application/gateway:latest
          name: gateway
          ports:
            - containerPort: 30000
              protocol: TCP
          volumeMounts:
            - mountPath: /run/spire/sockets
              name: spire-agent-socket
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
