apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks
  namespace: alpha-stocks-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stocks
  template:
    metadata:
      annotations:
        tratteria/inject-sidecar: "true"
        tratteria/agent-mode: "delegation"
      labels:
        app: stocks
    spec:
      serviceAccountName: stocks-service-account
      containers:
        - env:
            - name: STOCKS_DB_PATH
              value: /var/lib/stocks-db/stock.db
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: GATEWAY_SERVICE_SPIFFE_ID
              value: spiffe://dev.alphastocks.com/gateway
            - name: ORDER_SERVICE_SPIFFE_ID
              value: spiffe://dev.alphastocks.com/order
            - name: STOCKS_SERVICE_SPIFFE_ID
              value: spiffe://dev.alphastocks.com/stocks
            - name: TRAT_VERIFY_ENDPOINT
              value: http://localhost:9030/verify-trat
            - name: ENABLE_TRATS
              value: "${ENABLE_TRATS}"
          image: ghcr.io/tratteria/example-application/stocks:latest
          name: stocks
          ports:
            - containerPort: 8070
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8070
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - mountPath: /var/lib/stocks-db
              name: stocks-db
            - mountPath: /run/spire/sockets
              name: spire-agent-socket
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: stocks-db
          persistentVolumeClaim:
            claimName: stocks-db
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
