apiVersion: v1
kind: Service
metadata:
  name: tratteria
  namespace: alpha-stocks-dev  # Replace [your-namespace] with the desired Kubernetes namespace
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    app: tratteria
    